claude-3-5-msn: &claude-3-5-sonnet
  msn: anthropic/claude-3-5-sonnet-20240620/anthropic-beta=max-tokens-3-5-sonnet-2024-07-15

gpt4-msn: &gpt4-o-mini
  msn: openai/gpt-4o-mini-2024-07-18

agents:
  Coder:
    *gpt4-o-mini
  default:  
    *claude-3-5-sonnet
